excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://lucapassaro.github.io
title: Luca Passaro's Blog
tagline: A log of everyday life
description: My awesome new site
paginate: 5